name: CI/CD for NodeJS App

on:
  push:
    branches: [ !test ] #shouldn't be deployed if the branch-name is "test"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          DEPLOYED_FROM: ${{ github.ref }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:$DEPLOYED_FROM .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:$DEPLOYED_FROM

      - name: Deploy to staging/production (optional, replace with desired deployment strategy)
        if: ${{ env.DEPLOYED_FROM != 'master' }}